DELETE http://localhost:3000/api/1.0/notes/2
Content-Type: application/json
Cookie: _Host-sessionJWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1SUQiOjEsInVzZXJuYW1lIjoiVHJvbGwzMjEiLCJlbWFpbCI6ImF0aWxhLmdodWx3YW5pQGdtYWlsLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAxLTI0VDAxOjQ0OjA5LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wMS0yNFQwMTo0NDowOS4wMDBaIiwiaWF0IjoxNzM3NjgzMDkzLCJleHAiOjE3Mzc3MDEwOTN9.O1FXius2dkQpNhMUXskOpSm_mQKkSUHvt37oRyE9kgY;

# Expect notes deleted